<div class="clearfix wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp; text-align: justify;padding-right: 20px;padding-left:20px">

                        <h3>WHAT IS E-WASTE?</h3>
<p>“E-waste”is a term used to describe discarded and end-of-life electronic products. Waste from Electrical and Electronic Equipment (WEEE) is one of the fastest growing types of hazardous waste globally. “E-waste” consists of waste from electronic products such as personal computers, mobile telephones and household appliances (e.g: televisions, washing machines, air conditioners, microwaves, refrigerators, etc). Technical development of electrical and electronic equipment has shown a rapid growth over the past few decades with the manufacturers constantly offering new and better devices. Since, for many electronic equipment, it is often cheaper to buy a new device than to repair it, the rate of disposal has been on the rise. Thus, more and more obsolete equipment is thrown away or given to scrap dealers/collectors and the amount of e-waste has significantly increased posing a serious problem.</p>
<p>E-waste is classified as hazardous waste due to its toxic ingredients, including heavy metals and harmful chemicals such as lead, cadmium, mercury, arsenic etc., with the potential to pollute the environment and damage human health when it is processed, recycled or disposed of using informal processes.</p>
<p>The growing awareness and sensitization of the increasing environmental impacts associated with E-waste and the development in the WEEE sector with the increasing occurrence of E-waste and its disposal have triggered initiatives all over India.</p>
<p>It is largely found in Asian countries that waste treatment facilities exist for the sole purpose of generating profit with absolutely no concern for the environment. Electronic circuitry contains valuable elements which are simply stripped from the E-waste. The residue then, is either burned or dumped. This residue contains many extremely harmful elements like cadmium, lead, arsenic, mercury, nonylphenol, plastics including PVC and many others which take their toll on the surrounding flora, fauna and the ecosystems that they sustain.Even in the so called organized sector, it’s the same despicable scenario where, the “Recyclers” obtain the E-waste at subsidized rates or through donations from large corporations under the pretext of Recycling; and sell it off in the local scrap market for a hefty profit. Several such cases have been documented. Other malpractices involve false representation of information to import E-waste from developed countries. Corrupt and greedy Recyclers are jeopardizing the health of the planet and misleading the stakeholders.</p>


                                       
                </div>
                <div class="clearfix wow fadeInUp animated"  style="visibility: visible; animation-name: fadeInUp;text-align: justify;padding-right: 20px;padding-left:20px">

                    <h3>HAZARDS OF E-WASTE</h3>
<p>Numerous electronic gadgets, including PCs, laptops, DVDs, MP3 players, printers, mobile phones, washing machines, home appliances, televisions and other equipments, are bought and sold every day. Although most of them constitute an indispensable part of our everyday lives, their hazardous effects on the environment and health cannot be overlooked. Once these electronic equipments become obsolete, they are dumped into landfills, making them hazardous for the environment.</p>
<p>In landfills, E-waste represents 2% of trash but equals to 70% of overall toxic waste. In the US, “the Department of Toxic Substances Control has determined that most electronic devices are toxic”.</p>
<p>When E-waste is disposed of or recycled without any controls, there are predictable negative impacts on the environment and human health. E-waste contains more than 1000 different substances, many of which are toxic substances such as lead, mercury, cadmium, polychlorinated biphenyls (PCBs), brominated flame retardants (BFRs), plastic casings, cables and polyvinyl chloride (PVC) cable insulation that release highly toxic brominated and chlorinated dioxins and furans– two of the most deadly persistent organic pollutants (POPs); when burned to retrieve copper from the wires. Even high traces of cancer causing polycyclic aromatic hydrocarbons (PAHs) are found in the emissions and the ash of E-waste. Generally after being stripped of its valuable content, the residue that’s left behind ends up being burnt or thrown away in landfills. Burning/incinerating the waste exposes its harmful contents directly into the atmosphere; in other words, endangering the plant and animal life in that environment, whereas, landfill dumping results in the elements being leached into the soil, and subsequently into the surface/ground water. This affects the flora and the fauna of that environment.</p>
<p>Unorganized and informal sectors use primitive methods to separate and recover precious metals from the PCBs. This method mainly involves dipping the PCBs in concentrated mix of acids until the precious metals are liberated from the circuit boards. This type of method is estimated to recover 8-10 % of the total recoverable elements as opposed to 90-95% recovery obtained in the formal, organized sector. Upon completion, the used acids are carelessly dumped in the closest drains or rivers. Water samples tested in and around the areas where such activities are carried out have been found to have dangerously high levels of toxins for human contact, let alone human consumption.</p>

                    
            
                </div>