<div class="container-fluid" style="background-color: orange">
	<center>
		This is the front page on the opening off app
	</center> 
	 <head><style>
  /* Make the image fully responsive */
  .carousel-inner img {
      width: 600px;
      height: 400px;
      margin: 0 auto;
  }

  </style>
</head>
	<div class="container mt-3">

<center>
	<h2>The waste generated by us....!!!</h2>
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ul>
  
  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<?php echo base_url('asset/images/3.jpg'); ?>"  width="500" height="500">
    </div>
    <div class="carousel-item">
      <img src="<?php echo base_url('asset/images/2.jpg'); ?>"  width="500" height="500">
    </div>
    <div class="carousel-item">
      <img src="<?php echo base_url('asset/images/1.jpg'); ?>"  width="500" height="500">
    </div>
  </div>
  
  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
</center>
</div>
<div>